baseURL = "https://blog.nicro.land/"
title = "Geek w/ god complex"
copyright = ""

theme = "nicro"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "and his senseless ramblings..."
title404 = "Nothing to see here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "images/lost-and-found.gif" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Nic Roland"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#8AAAE5"
hideMainMenu = true

[params.sidebar]
enable = true

[params.widgets]
header = []
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "nicroland9@gmail.com"
github = "nicr9"
linkedin = "nicroland"
twitter = "nicr9_"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"


[menu]
    [[menu.main]]
    name = "About"
    url = "/about/"

    [[menu.main]]
    name = "Posts"
    url = "/posts/"

    [[menu.main]]
    name = "Slides"
    url = "https://slides.nicro.land"

    [[menu.main]]
    name = "Projects"
    url = "/my-side-projects/"

[blackfriday]
hrefTargetBlank = true

[languages.en]
languageName = "English"
weight = 1

[languages.en.params]
lang = "en-gb"
